# Server Configuration
server:
  port: 8080

# JPA Settings
spring:
  application:
    name: user-service # Logical name for the service (used by Eureka)

  jpa:
    hibernate:
      ddl-auto: create-drop

  # Datasource Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/users
    username: postgres
    password: 123456789
    driver-class-name: org.postgresql.Driver

  cloud:
    compatibility-verifier:
      enabled:
        false

# Eureka Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # Eureka server endpoint
    fetch-registry: true # Fetch registry information
    register-with-eureka: true # Register this service with Eureka

  instance:
    prefer-ip-address: true # Use IP address instead of hostname in Eureka registry
    instance-id: ${spring.application.name}:${server.port} # Unique instance ID in Eureka

jwt:
  secret: bc4996f25409935536e23ff35b8d8ea734851662d5bdf97e5854f2bde7c8255b111868b1c4ba58d3795332226f28a0eb5d7ce318b632b06c8392b6c54c147f4d

frontend:
  url: http://localhost:5173

