server:
  port: 8081

spring:
  application:
    name: reservation-service

  jpa:
    hibernate:
      ddl-auto: create-drop

  datasource:
    url: jdbc:postgresql://localhost:5432/restaurants
    username: postgres
    password: 123456789
    driver-class-name: org.postgresql.Driver

jwt:
  secret: bc4996f25409935536e23ff35b8d8ea734851662d5bdf97e5854f2bde7c8255b111868b1c4ba58d3795332226f28a0eb5d7ce318b632b06c8392b6c54c147f4d