spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      global cors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:5173"
            allowedMethods: "*"
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
server:
  port: '7777'
eureka:
  client:
    enabled: true
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: '30'
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway